version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: reddit_watcher
      POSTGRES_USER: reddit_watcher_user
      POSTGRES_PASSWORD: dev_password_123
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reddit_watcher_user -d reddit_watcher"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass dev_redis_123
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
